### ISSUE TITLE
ArrayIndexOutOfBoundsException  测试：一加手机，红米

### ISSUE THREAD

**Issue by Veryed-VS** [pangguoming/android-camera-color-picker#1]
java.lang.ArrayIndexOutOfBoundsException: length=1382400; index=2073600
                                                                               at com.pangguoming.whatcolor.CameraActivity.decodeYUV420SP(CameraActivity.java:101)
                                                                               at com.pangguoming.whatcolor.CameraActivity.onPreviewFrame(CameraActivity.java:86)
                                                                               at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1150)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by pangguoming** [comment]
嗯，是计算屏幕中心点像素坐标错误。当时我考虑过 不同屏幕尺寸 ，在计算这个中心点的时候是不一样的。 你可以自己写个更好的 算法，把我的替换掉

**Comment by Veryed-VS** [comment]
未能找到问题所在。

**Comment by pangguoming** [comment]
就是 个数组计算 出界，很简单的，你先尝试自己修复。我这边没有Android开发环境，有空再修复

**Comment by Veryed-VS** [comment]
好吧。不用了。我已经自己写了个。

**Comment by pangguoming** [comment]
好的

**Comment by programmer1058** [comment]
hi guys. my problem is "ArrayIndexOutOfBoundsException".
can anyone help me?

**Comment by pangguoming** [comment]
@programmer1058  i know that bug, Different mobile phones have different screen sizes.  you had better adjust the code according to different screen size.

**Comment by Veryed-VS** [comment]
I have rewritten one, which can see this, and integration is simple. "https://github.com/Veryed-VS/Camera-Color-Picker"

**Comment by programmer1058** [comment]
Tnx man.

در تاریخ سه‌شنبه ۱۴ اوت ۲۰۱۸،‏ ۷:۳۷ 建明 <notifications@github.com> نوشت:
